downloadValuesToExcel(list(input$temp, input$press, input$humid, 
                           g_vpw, g_sos, g_dvi, g_aid, g_imp),
                      list(input$t1ui, input$t2ui, input$t3ui), 
                      list(input$r1ui, input$r2ui, input$r3ui),
                      list(input$phi1ui, input$phi2ui, input$phi3ui),
                      list(input$d1ui, input$d2ui, input$d3ui),
                      list(input$leftEdge, input$rightEdge, input$thresh),
                      list(input$r1ui * (pi / input$phi1ui)^0.5, 
                           input$r2ui * (pi / input$phi2ui)^0.5, 
                           input$r3ui * (pi / input$phi3ui)^0.5),
                      cbind(seq(g_lb_absorption, g_ub_absorption, by = g_no_of_calc_points), 
                            calcAbsorptionMPPVecModels(seq(g_lb_absorption, g_ub_absorption, by = g_no_of_calc_points), 
                                                 g_environ = list(input$press, input$temp, input$humid/100), 
                                                 g_mpp = list(list(input$d1ui, input$d2ui, input$d3ui), 
                                                              list(input$t1ui, input$t2ui, input$t3ui), 
                                                              list(input$r1ui, input$r2ui, input$r3ui), 
                                                              list(input$phi1ui, input$phi2ui, input$phi3ui)),
                                                 model.fname = list("calcSurfaceResistanceRuiz",
                                                                    "calcSurfaceResistance",
                                                                    "calcSurfaceResistanceAtallaSgardSimple",
                                                                    "calcSurfaceResistanceMaaExact"))),
                      file)